"""Generate a self-extracting CIRCUITPY installer as a single code.py.

The payload rides in trailing comment lines. CircuitPython's lexer reads
through a 255-byte buffer and discards comments without allocating, so the
file compiles cheaply however large the payload is. At run time the installer
reopens /code.py, walks past the header and inflates one member at a time, so
peak RAM is the largest single file rather than the whole tree.
"""

import base64
import os
import zlib

MARKER = "# ---8<--- folder2uf2 payload, do not edit below this line"

STUB = '''\
# Self-extracting CircuitPython installer, generated by folder2uf2.
# Drag this onto CIRCUITPY. It unpacks itself and reboots.
import binascii
import microcontroller
import os
import storage
import time
import zlib

MARKER = "{marker}"


def _mkdirs(path):
    parts = path.split("/")[:-1]
    grown = ""
    for part in parts:
        if not part:
            continue
        grown += "/" + part
        try:
            os.mkdir(grown)
        except OSError:
            pass


def _members():
    """Yield (path, data) one at a time, holding only one member in RAM.

    Base64 is decoded line by line into a bytearray. Joining the lines into
    one string first costs an extra 4/3 of the compressed size, which
    overflows a 264KB RP2040 well before the decompression itself would.
    """
    with open("/code.py", "r") as f:
        for line in f:
            if line.rstrip("\\n") == MARKER:
                break
        path = None
        buf = None
        pos = 0
        for line in f:
            line = line.rstrip("\\n")
            if not line.startswith("#"):
                continue
            body = line[1:]
            if body.startswith(">"):
                if path is not None:
                    # memoryview slice, so the exact length is passed
                    # without copying the buffer
                    yield path, zlib.decompress(memoryview(buf)[:pos])
                n, _, path = body[1:].partition("|")
                # preallocate: growing a bytearray reallocates and the spike
                # is what overflows a 264KB RP2040
                buf = bytearray((int(n) * 3) // 4 + 3)
                pos = 0
            elif path is not None:
                chunk = binascii.a2b_base64(body)
                buf[pos:pos + len(chunk)] = chunk
                pos += len(chunk)
        if path is not None:
            yield path, zlib.decompress(memoryview(buf)[:pos])


print("folder2uf2 installer: unpacking")
# Let the host flush anything still cached before the drive disappears.
time.sleep({settle})
storage.unsafe_disable_usb_drive()

try:
    deferred = None
    count = 0
    for path, data in _members():
        if path == "code.py":
            deferred = data
            continue
        _mkdirs(path)
        with open("/" + path, "wb") as out:
            out.write(data)
        count += 1
        print("  " + path)

    # code.py last: until it lands, a crash leaves the installer rerunnable.
    if deferred is not None:
        with open("/code.py.new", "wb") as out:
            out.write(deferred)
        os.rename("/code.py.new", "/code.py")
        count += 1
except Exception as e:  # noqa: BLE001 - must not strand the user
    # Give the drive back, or CIRCUITPY stays hidden and the installer
    # reruns and fails on every boot, locking the user out entirely.
    print("install failed:", e)
    print("re-enabling CIRCUITPY so you can remove this file")
    storage.enable_usb_drive()
    raise

print("unpacked %d files, resetting" % count)
time.sleep(0.5)
# Hard reset, not supervisor.reload(): a soft reload leaves the USB drive
# disabled, so CIRCUITPY never comes back for the user.
microcontroller.reset()
'''


def build(src, settle=3.0, wrap=120):
    """Return the text of a self-extracting code.py for the tree at src."""
    out = [STUB.format(marker=MARKER, settle=settle), MARKER]
    total_raw = 0
    biggest = 0
    for path in sorted(_walk(src)):
        full = os.path.join(src, path)
        raw = open(full, "rb").read()
        total_raw += len(raw)
        biggest = max(biggest, len(raw))
        blob = base64.b64encode(zlib.compress(raw, 9)).decode("ascii")
        out.append("#>%d|%s" % (len(blob), path.replace(os.sep, "/")))
        for i in range(0, len(blob), wrap):
            out.append("#" + blob[i:i + wrap])
    return "\n".join(out) + "\n", total_raw, biggest


def _walk(src):
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs
                   if d not in (".fseventsd", ".Trashes", "__pycache__")]
        for name in files:
            if name.startswith("._") or name in (
                    ".metadata_never_index", ".Trash-1000", "boot_out.txt"):
                continue
            yield os.path.relpath(os.path.join(root, name), src)
